/**
 * [Step 4] Supabase DB에 단어 데이터 적재
 * PRD 9.4: 최종 데이터를 words 테이블에 bulk upsert
 * 
 * RLS 우회를 위해 Supabase CLI migration을 자동 생성하여 push
 */
import fs from 'fs';
import path from 'path';

const DATA_DIR = path.resolve(__dirname, 'data');
const FINAL = path.resolve(DATA_DIR, 'final_words.json');
const MIGRATIONS_DIR = path.resolve(__dirname, '..', '..', 'supabase', 'migrations');

interface FinalWord {
  word: string;
  meaning: string;
  pos: string;
  difficulty: number;
  source: string;
  corpus_freq: number;
}

function escapeSQL(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  console.log('[4] Loading final_words.json...');
  const words: FinalWord[] = JSON.parse(fs.readFileSync(FINAL, 'utf-8'));

  // 미번역(placeholder) 단어는 제외 — 뜻이 있는 것만 DB에 넣기
  const translated = words.filter(w => !w.meaning.startsWith('('));
  console.log(`[4] ${translated.length} translated words (skipping ${words.length - translated.length} untranslated)`);

  // SQL 마이그레이션 파일 생성
  const timestamp = new Date().toISOString().replace(/[-:T.Z]/g, '').slice(0, 14);
  const migrationFile = path.resolve(MIGRATIONS_DIR, `${timestamp}_seed_pipeline_words.sql`);

  let sql = '-- Auto-generated by pipeline step 4\n';
  sql += '-- Seed words from NGSL/CEFR-J pipeline\n\n';

  for (const w of translated) {
    sql += `INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('${escapeSQL(w.word)}', '${escapeSQL(w.meaning)}', '${escapeSQL(w.pos)}', ${w.difficulty}, '${escapeSQL(w.source)}') ON CONFLICT (word) DO UPDATE SET meaning = EXCLUDED.meaning, pos = EXCLUDED.pos, difficulty = EXCLUDED.difficulty, source = EXCLUDED.source;\n`;
  }

  fs.mkdirSync(MIGRATIONS_DIR, { recursive: true });
  fs.writeFileSync(migrationFile, sql);
  console.log(`[4] Generated migration: ${path.basename(migrationFile)}`);
  console.log(`[4] Run 'bunx supabase db push' to apply to remote DB`);
}

main().catch(console.error);
