export const dummyWords = [
  { word: 'abandon', meaning: '버리다, 포기하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'absolute', meaning: '절대적인, 완전한', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'absorb', meaning: '흡수하다, 받아들이다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'abstract', meaning: '추상적인', pos: 'adj', difficulty: 3, source: 'NGSL' },
  { word: 'abundant', meaning: '풍부한, 많은', pos: 'adj', difficulty: 3, source: 'CEFR-J' },
  { word: 'academic', meaning: '학업의, 학구적인', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'accelerate', meaning: '가속하다, 촉진하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'acceptable', meaning: '받아들일 수 있는', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'access', meaning: '접근, 접근하다', pos: 'noun', difficulty: 2, source: 'NGSL' },
  { word: 'accommodate', meaning: '수용하다, 편의를 제공하다', pos: 'verb', difficulty: 4, source: 'CEFR-J' },
  { word: 'accompany', meaning: '동반하다, 동행하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'accomplish', meaning: '성취하다, 완수하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'accurate', meaning: '정확한', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'accuse', meaning: '고발하다, 비난하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'achieve', meaning: '달성하다, 성취하다', pos: 'verb', difficulty: 1, source: 'NGSL' },
  { word: 'acquire', meaning: '습득하다, 얻다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'adapt', meaning: '적응하다, 맞추다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'adequate', meaning: '적당한, 충분한', pos: 'adj', difficulty: 3, source: 'NGSL' },
  { word: 'adjust', meaning: '조정하다, 적응하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'administer', meaning: '관리하다, 투여하다', pos: 'verb', difficulty: 4, source: 'NGSL' },
  { word: 'admire', meaning: '존경하다, 칭찬하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'admit', meaning: '인정하다, 허락하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'adopt', meaning: '채택하다, 입양하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'advance', meaning: '전진, 발전', pos: 'noun', difficulty: 2, source: 'NGSL' },
  { word: 'advantage', meaning: '이점, 유리', pos: 'noun', difficulty: 1, source: 'NGSL' },
  { word: 'advocate', meaning: '옹호하다, 지지하다', pos: 'verb', difficulty: 4, source: 'CEFR-J' },
  { word: 'affect', meaning: '영향을 미치다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'afford', meaning: '여유가 있다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'agency', meaning: '대행사, 기관', pos: 'noun', difficulty: 2, source: 'NGSL' },
  { word: 'aggressive', meaning: '공격적인, 적극적인', pos: 'adj', difficulty: 3, source: 'NGSL' },
  { word: 'agriculture', meaning: '농업', pos: 'noun', difficulty: 3, source: 'CEFR-J' },
  { word: 'alien', meaning: '외계인, 외국의', pos: 'noun', difficulty: 3, source: 'NGSL' },
  { word: 'allocate', meaning: '할당하다, 배분하다', pos: 'verb', difficulty: 4, source: 'NGSL' },
  { word: 'allow', meaning: '허락하다, 인정하다', pos: 'verb', difficulty: 1, source: 'NGSL' },
  { word: 'alter', meaning: '바꾸다, 변경하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'alternative', meaning: '대안, 대체의', pos: 'noun', difficulty: 3, source: 'NGSL' },
  { word: 'amaze', meaning: '놀라게 하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'ambition', meaning: '야망, 포부', pos: 'noun', difficulty: 3, source: 'NGSL' },
  { word: 'analyze', meaning: '분석하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'ancient', meaning: '고대의, 아주 오래된', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'announce', meaning: '발표하다, 알리다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'annual', meaning: '매년의, 연간의', pos: 'adj', difficulty: 2, source: 'NGSL' },
  { word: 'anticipate', meaning: '예상하다, 기대하다', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'anxiety', meaning: '불안, 걱정', pos: 'noun', difficulty: 3, source: 'NGSL' },
  { word: 'apologize', meaning: '사과하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'apparent', meaning: '명백한, 분명한', pos: 'adj', difficulty: 3, source: 'NGSL' },
  { word: 'appeal', meaning: '호소하다, 매력', pos: 'verb', difficulty: 3, source: 'NGSL' },
  { word: 'appear', meaning: '나타나다, ~인 것 같다', pos: 'verb', difficulty: 1, source: 'NGSL' },
  { word: 'apply', meaning: '적용하다, 지원하다', pos: 'verb', difficulty: 2, source: 'NGSL' },
  { word: 'appreciate', meaning: '감사하다, 진가를 알아보다', pos: 'verb', difficulty: 3, source: 'NGSL' },
];
