INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('abandon', '버리다, 포기하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('absolute', '절대적인, 완전한', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('absorb', '흡수하다, 받아들이다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('abstract', '추상적인', 'adj', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('abundant', '풍부한, 많은', 'adj', 3, 'CEFR-J') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('academic', '학업의, 학구적인', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accelerate', '가속하다, 촉진하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('acceptable', '받아들일 수 있는', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('access', '접근, 접근하다', 'noun', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accommodate', '수용하다, 편의를 제공하다', 'verb', 4, 'CEFR-J') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accompany', '동반하다, 동행하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accomplish', '성취하다, 완수하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accurate', '정확한', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('accuse', '고발하다, 비난하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('achieve', '달성하다, 성취하다', 'verb', 1, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('acquire', '습득하다, 얻다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('adapt', '적응하다, 맞추다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('adequate', '적당한, 충분한', 'adj', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('adjust', '조정하다, 적응하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('administer', '관리하다, 투여하다', 'verb', 4, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('admire', '존경하다, 칭찬하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('admit', '인정하다, 허락하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('adopt', '채택하다, 입양하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('advance', '전진, 발전', 'noun', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('advantage', '이점, 유리', 'noun', 1, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('advocate', '옹호하다, 지지하다', 'verb', 4, 'CEFR-J') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('affect', '영향을 미치다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('afford', '여유가 있다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('agency', '대행사, 기관', 'noun', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('aggressive', '공격적인, 적극적인', 'adj', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('agriculture', '농업', 'noun', 3, 'CEFR-J') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('alien', '외계인, 외국의', 'noun', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('allocate', '할당하다, 배분하다', 'verb', 4, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('allow', '허락하다, 인정하다', 'verb', 1, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('alter', '바꾸다, 변경하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('alternative', '대안, 대체의', 'noun', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('amaze', '놀라게 하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('ambition', '야망, 포부', 'noun', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('analyze', '분석하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('ancient', '고대의, 아주 오래된', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('announce', '발표하다, 알리다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('annual', '매년의, 연간의', 'adj', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('anticipate', '예상하다, 기대하다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('anxiety', '불안, 걱정', 'noun', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('apologize', '사과하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('apparent', '명백한, 분명한', 'adj', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('appeal', '호소하다, 매력', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('appear', '나타나다, ~인 것 같다', 'verb', 1, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('apply', '적용하다, 지원하다', 'verb', 2, 'NGSL') ON CONFLICT (word) DO NOTHING;
INSERT INTO words (word, meaning, pos, difficulty, source) VALUES ('appreciate', '감사하다, 진가를 알아보다', 'verb', 3, 'NGSL') ON CONFLICT (word) DO NOTHING;